### ISSUE TITLE
Instagram card urls

### ISSUE THREAD

**Issue by vzjrz** [cecekpawon/Traditional-Twitter-RT#1]
I wasn't getting instagram cards anymore and it seems like instagram is using new urls pointed to `https://www.instagram.com`
I changed `insta_a` to:
`insta_a = e.text().trim().match(/https?:\/\/(www\.)?(instagr\.am|instagram\.com)\/p\/([^\/\s]+)/ig),`
and it fixed it for me.

**Comment by cecekpawon** [comment]
Tested & work flawlessly, thank you @vzjrz bump to 5.5.7
